import { HttpClientTestingModule, HttpTestingController, TestRequest } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';

import ControlModule from '../control.module';
import RiotMatchFetcher from './RiotMatchFetcher.service';
import { MatchFetcher, MatchFetcherError } from './MatchFetcher.service';
import MockChampionFetcher from '../champions/MockChampionFetcher.service';
import { ChampionFetcher } from '../champions/ChampionFetcher.service';
import { environment } from 'src/environments/environment';
import { Match } from 'src/app/models';


describe('RiotMatchFetcher', () => {
    let httpTestingController: HttpTestingController;
    let fetcher: MatchFetcher;
    const API_KEY: string = environment.RIOT_API_KEY;
    const STUB_ID: number = 862100018;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [ ControlModule, HttpClientTestingModule ],
            providers: [
                { provide: ChampionFetcher, useClass: MockChampionFetcher }
            ]
        });
        fetcher = TestBed.inject(RiotMatchFetcher);
        httpTestingController = TestBed.inject(HttpTestingController);
    });

    it('fetch(): fetches and parses a match', async () => {
        const matchPromise: Promise<Match> = fetcher.fetch(STUB_ID);
        httpTestingController.expectOne(`/lol/match/v4/matches/${STUB_ID}?api_key=${API_KEY}`).flush(mockMatchResponse);
        const match: Match = await matchPromise;
        console.log(match);
        expect(match).toBeTruthy();
    });

    it('fetch(): fails grecefully when a match can\'t be fetched', async () => {
        const matchPromise: Promise<Match> = fetcher.fetch(STUB_ID);
        const ERROR_404: object = { status: 404, statusText: 'Not Found' };
        httpTestingController.expectOne(`/lol/match/v4/matches/${STUB_ID}?api_key=${API_KEY}`).flush('deliberate 404 error', ERROR_404);
        await expectAsync(matchPromise).toBeRejectedWith(
            new Error(MatchFetcherError.FETCH_ERROR)
        );
    });
});

const mockMatchResponse: object = {
    "gameId": 862100018,
    "platformId": "LA1",
    "gameCreation": 1589134430921,
    "gameDuration": 1311,
    "queueId": 830,
    "mapId": 11,
    "seasonId": 13,
    "gameVersion": "10.9.318.6057",
    "gameMode": "CLASSIC",
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "teamId": 100,
            "win": "Win",
            "firstBlood": true,
            "firstTower": true,
            "firstInhibitor": true,
            "firstBaron": false,
            "firstDragon": true,
            "firstRiftHerald": false,
            "towerKills": 11,
            "inhibitorKills": 2,
            "baronKills": 0,
            "dragonKills": 1,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": []
        },
        {
            "teamId": 200,
            "win": "Fail",
            "firstBlood": false,
            "firstTower": false,
            "firstInhibitor": false,
            "firstBaron": false,
            "firstDragon": false,
            "firstRiftHerald": false,
            "towerKills": 0,
            "inhibitorKills": 0,
            "baronKills": 0,
            "dragonKills": 0,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": []
        }
    ],
    "participants": [
        {
            "participantId": 1,
            "teamId": 100,
            "championId": 226,
            "spell1Id": 6,
            "spell2Id": 7,
            "stats": {
                "participantId": 1,
                "win": true,
                "item0": 1027,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 0,
                "kills": 0,
                "deaths": 0,
                "assists": 0,
                "largestKillingSpree": 0,
                "largestMultiKill": 0,
                "killingSprees": 0,
                "longestTimeSpentLiving": 0,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 0,
                "magicDamageDealt": 0,
                "physicalDamageDealt": 0,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 0,
                "magicDamageDealtToChampions": 0,
                "physicalDamageDealtToChampions": 0,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 0,
                "totalUnitsHealed": 0,
                "damageSelfMitigated": 0,
                "damageDealtToObjectives": 0,
                "damageDealtToTurrets": 0,
                "visionScore": 0,
                "timeCCingOthers": 0,
                "totalDamageTaken": 0,
                "magicalDamageTaken": 0,
                "physicalDamageTaken": 0,
                "trueDamageTaken": 0,
                "goldEarned": 4726,
                "goldSpent": 350,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 0,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 0,
                "champLevel": 4,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 0,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 0,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 24,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8138,
                "perk4Var1": 0,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8105,
                "perk5Var1": 2,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 1,
                "creepsPerMinDeltas": {
                    "10-20": 0,
                    "0-10": 0
                },
                "xpPerMinDeltas": {
                    "10-20": 13.7,
                    "0-10": 103.3
                },
                "goldPerMinDeltas": {
                    "10-20": 213.6,
                    "0-10": 150
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 0,
                    "0-10": 0
                },
                "role": "DUO_SUPPORT",
                "lane": "TOP"
            }
        },
        {
            "participantId": 2,
            "teamId": 100,
            "championId": 81,
            "spell1Id": 6,
            "spell2Id": 7,
            "stats": {
                "participantId": 2,
                "win": true,
                "item0": 3071,
                "item1": 1004,
                "item2": 1056,
                "item3": 2031,
                "item4": 1054,
                "item5": 3801,
                "item6": 3364,
                "kills": 5,
                "deaths": 3,
                "assists": 3,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "killingSprees": 2,
                "longestTimeSpentLiving": 533,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 11319,
                "magicDamageDealt": 2360,
                "physicalDamageDealt": 8958,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 1877,
                "magicDamageDealtToChampions": 571,
                "physicalDamageDealtToChampions": 1306,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 1007,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 4372,
                "damageDealtToObjectives": 1586,
                "damageDealtToTurrets": 1586,
                "visionScore": 0,
                "timeCCingOthers": 1,
                "totalDamageTaken": 6490,
                "magicalDamageTaken": 1155,
                "physicalDamageTaken": 5335,
                "trueDamageTaken": 0,
                "goldEarned": 6522,
                "goldSpent": 4775,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 8,
                "neutralMinionsKilled": 4,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 16,
                "champLevel": 9,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 142,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 167,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 9,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8135,
                "perk3Var1": 160,
                "perk3Var2": 3,
                "perk3Var3": 0,
                "perk4": 9111,
                "perk4Var1": 507,
                "perk4Var2": 160,
                "perk4Var3": 0,
                "perk5": 8014,
                "perk5Var1": 87,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 2,
                "creepsPerMinDeltas": {
                    "10-20": 0.2,
                    "0-10": 0.6
                },
                "xpPerMinDeltas": {
                    "10-20": 325,
                    "0-10": 76.5
                },
                "goldPerMinDeltas": {
                    "10-20": 328.1,
                    "0-10": 190.39999999999998
                },
                "csDiffPerMinDeltas": {
                    "10-20": -0.30000000000000004,
                    "0-10": 0.09999999999999998
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 74.80000000000001,
                    "0-10": -137.7
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 363.70000000000005,
                    "0-10": 94.1
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -810.3,
                    "0-10": -522.4000000000001
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 3,
            "teamId": 100,
            "championId": 103,
            "spell1Id": 12,
            "spell2Id": 7,
            "stats": {
                "participantId": 3,
                "win": true,
                "item0": 1055,
                "item1": 3072,
                "item2": 3006,
                "item3": 3087,
                "item4": 1038,
                "item5": 1037,
                "item6": 3340,
                "kills": 6,
                "deaths": 3,
                "assists": 5,
                "largestKillingSpree": 5,
                "largestMultiKill": 2,
                "killingSprees": 1,
                "longestTimeSpentLiving": 728,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 68509,
                "magicDamageDealt": 4367,
                "physicalDamageDealt": 61062,
                "trueDamageDealt": 3080,
                "largestCriticalStrike": 389,
                "totalDamageDealtToChampions": 8683,
                "magicDamageDealtToChampions": 12,
                "physicalDamageDealtToChampions": 8671,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 697,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 5910,
                "damageDealtToObjectives": 10298,
                "damageDealtToTurrets": 10298,
                "visionScore": 0,
                "timeCCingOthers": 0,
                "totalDamageTaken": 7285,
                "magicalDamageTaken": 1170,
                "physicalDamageTaken": 6115,
                "trueDamageTaken": 0,
                "goldEarned": 10770,
                "goldSpent": 9825,
                "turretKills": 4,
                "inhibitorKills": 1,
                "totalMinionsKilled": 93,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 27,
                "champLevel": 12,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 6,
                "wardsKilled": 0,
                "firstBloodKill": true,
                "firstBloodAssist": false,
                "firstTowerKill": true,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8005,
                "perk0Var1": 327,
                "perk0Var2": 269,
                "perk0Var3": 58,
                "perk1": 9111,
                "perk1Var1": 411,
                "perk1Var2": 220,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 13,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 229,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8233,
                "perk4Var1": 13,
                "perk4Var2": 10,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 14,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 3,
                "creepsPerMinDeltas": {
                    "10-20": 6,
                    "0-10": 3.2
                },
                "xpPerMinDeltas": {
                    "10-20": 548,
                    "0-10": 376
                },
                "goldPerMinDeltas": {
                    "10-20": 606.3,
                    "0-10": 358.6
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 348,
                    "0-10": 380.5
                },
                "role": "DUO_SUPPORT",
                "lane": "TOP"
            }
        },
        {
            "participantId": 4,
            "teamId": 100,
            "championId": 350,
            "spell1Id": 6,
            "spell2Id": 7,
            "stats": {
                "participantId": 4,
                "win": true,
                "item0": 2423,
                "item1": 2010,
                "item2": 2003,
                "item3": 3072,
                "item4": 3006,
                "item5": 3087,
                "item6": 3340,
                "kills": 15,
                "deaths": 0,
                "assists": 1,
                "largestKillingSpree": 15,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 1306,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 93593,
                "magicDamageDealt": 15558,
                "physicalDamageDealt": 76434,
                "trueDamageDealt": 1600,
                "largestCriticalStrike": 905,
                "totalDamageDealtToChampions": 14783,
                "magicDamageDealtToChampions": 966,
                "physicalDamageDealtToChampions": 13817,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 824,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 5482,
                "damageDealtToObjectives": 4640,
                "damageDealtToTurrets": 4640,
                "visionScore": 0,
                "timeCCingOthers": 17,
                "totalDamageTaken": 8254,
                "magicalDamageTaken": 2032,
                "physicalDamageTaken": 6222,
                "trueDamageTaken": 0,
                "goldEarned": 11076,
                "goldSpent": 7250,
                "turretKills": 3,
                "inhibitorKills": 1,
                "totalMinionsKilled": 107,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 244,
                "champLevel": 16,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8351,
                "perk0Var1": 29,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8313,
                "perk1Var1": 0,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8345,
                "perk2Var1": 3,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8347,
                "perk3Var1": 0,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8451,
                "perk4Var1": 164,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8444,
                "perk5Var1": 750,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8300,
                "perkSubStyle": 8400,
                "statPerk0": 5007,
                "statPerk1": 5002,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 4,
                "creepsPerMinDeltas": {
                    "10-20": 6.5,
                    "0-10": 4
                },
                "xpPerMinDeltas": {
                    "10-20": 709.6,
                    "0-10": 595.7
                },
                "goldPerMinDeltas": {
                    "10-20": 544.4000000000001,
                    "0-10": 404.70000000000005
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 544.4,
                    "0-10": 247.5
                },
                "role": "DUO",
                "lane": "TOP"
            }
        },
        {
            "participantId": 5,
            "teamId": 100,
            "championId": 79,
            "spell1Id": 12,
            "spell2Id": 7,
            "stats": {
                "participantId": 5,
                "win": true,
                "item0": 3044,
                "item1": 3068,
                "item2": 3065,
                "item3": 3046,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 28,
                "deaths": 2,
                "assists": 3,
                "largestKillingSpree": 17,
                "largestMultiKill": 2,
                "killingSprees": 3,
                "longestTimeSpentLiving": 313,
                "doubleKills": 4,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 100846,
                "magicDamageDealt": 29548,
                "physicalDamageDealt": 69698,
                "trueDamageDealt": 1600,
                "largestCriticalStrike": 358,
                "totalDamageDealtToChampions": 29484,
                "magicDamageDealtToChampions": 4781,
                "physicalDamageDealtToChampions": 24703,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 7150,
                "totalUnitsHealed": 2,
                "damageSelfMitigated": 19553,
                "damageDealtToObjectives": 6513,
                "damageDealtToTurrets": 2115,
                "visionScore": 1,
                "timeCCingOthers": 28,
                "totalDamageTaken": 20385,
                "magicalDamageTaken": 2173,
                "physicalDamageTaken": 17211,
                "trueDamageTaken": 1000,
                "goldEarned": 13245,
                "goldSpent": 11800,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 96,
                "neutralMinionsKilled": 4,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 48,
                "champLevel": 15,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 1,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 1303,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8224,
                "perk1Var1": 92,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 14,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8138,
                "perk4Var1": 18,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8105,
                "perk5Var1": 15,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 5,
                "creepsPerMinDeltas": {
                    "10-20": 4.3,
                    "0-10": 3
                },
                "xpPerMinDeltas": {
                    "10-20": 625.6,
                    "0-10": 563.6
                },
                "goldPerMinDeltas": {
                    "10-20": 583,
                    "0-10": 477.6
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 955.7,
                    "0-10": 606.7
                },
                "role": "DUO_SUPPORT",
                "lane": "TOP"
            }
        },
        {
            "participantId": 6,
            "teamId": 200,
            "championId": 31,
            "spell1Id": 0,
            "spell2Id": 0,
            "stats": {
                "participantId": 6,
                "win": false,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 2,
                "deaths": 14,
                "assists": 0,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 217,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 13118,
                "magicDamageDealt": 2857,
                "physicalDamageDealt": 10260,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 5055,
                "magicDamageDealtToChampions": 933,
                "physicalDamageDealtToChampions": 4121,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 642,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 6067,
                "damageDealtToObjectives": 0,
                "damageDealtToTurrets": 0,
                "visionScore": 0,
                "timeCCingOthers": 0,
                "totalDamageTaken": 16633,
                "magicalDamageTaken": 1669,
                "physicalDamageTaken": 14964,
                "trueDamageTaken": 0,
                "goldEarned": 4858,
                "goldSpent": 200,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 10,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 0,
                "champLevel": 9,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 184,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 250,
                "perk1Var2": 15,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 14,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8138,
                "perk4Var1": 2,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8105,
                "perk5Var1": 5,
                "perk5Var2": 1,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 6,
                "creepsPerMinDeltas": {
                    "10-20": 0.4,
                    "0-10": 0.5
                },
                "xpPerMinDeltas": {
                    "10-20": 217.10000000000002,
                    "0-10": 217
                },
                "goldPerMinDeltas": {
                    "10-20": 225.6,
                    "0-10": 178.5
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 892.9,
                    "0-10": 481.29999999999995
                },
                "role": "DUO_SUPPORT",
                "lane": "TOP"
            }
        },
        {
            "participantId": 7,
            "teamId": 200,
            "championId": 412,
            "spell1Id": 0,
            "spell2Id": 0,
            "stats": {
                "participantId": 7,
                "win": false,
                "item0": 2003,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 0,
                "deaths": 4,
                "assists": 1,
                "largestKillingSpree": 0,
                "largestMultiKill": 0,
                "killingSprees": 0,
                "longestTimeSpentLiving": 957,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 2262,
                "magicDamageDealt": 996,
                "physicalDamageDealt": 1266,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 392,
                "magicDamageDealtToChampions": 50,
                "physicalDamageDealtToChampions": 342,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 15,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 1437,
                "damageDealtToObjectives": 32,
                "damageDealtToTurrets": 32,
                "visionScore": 0,
                "timeCCingOthers": 0,
                "totalDamageTaken": 3381,
                "magicalDamageTaken": 247,
                "physicalDamageTaken": 3133,
                "trueDamageTaken": 0,
                "goldEarned": 3178,
                "goldSpent": 200,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 2,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 0,
                "champLevel": 4,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8437,
                "perk0Var1": 32,
                "perk0Var2": 26,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 0,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8444,
                "perk2Var1": 50,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 9,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8224,
                "perk4Var1": 50,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8237,
                "perk5Var1": 7,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5002,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 7,
                "creepsPerMinDeltas": {
                    "10-20": 0,
                    "0-10": 0.2
                },
                "xpPerMinDeltas": {
                    "10-20": 0,
                    "0-10": 60
                },
                "goldPerMinDeltas": {
                    "10-20": 122.4,
                    "0-10": 122.7
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 0,
                    "0-10": 156
                },
                "role": "DUO_SUPPORT",
                "lane": "TOP"
            }
        },
        {
            "participantId": 8,
            "teamId": 200,
            "championId": 96,
            "spell1Id": 0,
            "spell2Id": 0,
            "stats": {
                "participantId": 8,
                "win": false,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 1,
                "deaths": 17,
                "assists": 0,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 223,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 9337,
                "magicDamageDealt": 2498,
                "physicalDamageDealt": 6839,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 4329,
                "magicDamageDealtToChampions": 1222,
                "physicalDamageDealtToChampions": 3107,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 0,
                "totalUnitsHealed": 0,
                "damageSelfMitigated": 6981,
                "damageDealtToObjectives": 55,
                "damageDealtToTurrets": 55,
                "visionScore": 0,
                "timeCCingOthers": 1,
                "totalDamageTaken": 20636,
                "magicalDamageTaken": 2250,
                "physicalDamageTaken": 18385,
                "trueDamageTaken": 0,
                "goldEarned": 3404,
                "goldSpent": 200,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 10,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 9,
                "champLevel": 8,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 353,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 250,
                "perk1Var2": 16,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 24,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8138,
                "perk4Var1": 2,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8105,
                "perk5Var1": 5,
                "perk5Var2": 1,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 8,
                "creepsPerMinDeltas": {
                    "10-20": 0.5,
                    "0-10": 0.5
                },
                "xpPerMinDeltas": {
                    "10-20": 250.2,
                    "0-10": 214.2
                },
                "goldPerMinDeltas": {
                    "10-20": 128.6,
                    "0-10": 139.1
                },
                "csDiffPerMinDeltas": {
                    "10-20": 0.30000000000000004,
                    "0-10": -0.09999999999999998
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -74.80000000000001,
                    "0-10": 137.7
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1174,
                    "0-10": 616.5
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 810.3,
                    "0-10": 522.4000000000001
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 9,
            "teamId": 200,
            "championId": 134,
            "spell1Id": 0,
            "spell2Id": 0,
            "stats": {
                "participantId": 9,
                "win": false,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 1,
                "deaths": 14,
                "assists": 0,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 245,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 8674,
                "magicDamageDealt": 3796,
                "physicalDamageDealt": 4878,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 2906,
                "magicDamageDealtToChampions": 1306,
                "physicalDamageDealtToChampions": 1599,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 846,
                "totalUnitsHealed": 2,
                "damageSelfMitigated": 14104,
                "damageDealtToObjectives": 0,
                "damageDealtToTurrets": 0,
                "visionScore": 0,
                "timeCCingOthers": 12,
                "totalDamageTaken": 20525,
                "magicalDamageTaken": 1861,
                "physicalDamageTaken": 18663,
                "trueDamageTaken": 0,
                "goldEarned": 3831,
                "goldSpent": 200,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 12,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 27,
                "champLevel": 8,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8437,
                "perk0Var1": 453,
                "perk0Var2": 314,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 0,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8444,
                "perk2Var1": 659,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 102,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8224,
                "perk4Var1": 409,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8237,
                "perk5Var1": 213,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5002,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 9,
                "creepsPerMinDeltas": {
                    "10-20": 0.8,
                    "0-10": 0.4
                },
                "xpPerMinDeltas": {
                    "10-20": 292.5,
                    "0-10": 133.6
                },
                "goldPerMinDeltas": {
                    "10-20": 202,
                    "0-10": 108.4
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1002.5,
                    "0-10": 608.2
                },
                "role": "SOLO",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 10,
            "teamId": 200,
            "championId": 254,
            "spell1Id": 0,
            "spell2Id": 0,
            "stats": {
                "participantId": 10,
                "win": false,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3340,
                "kills": 2,
                "deaths": 6,
                "assists": 0,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 521,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 39957,
                "magicDamageDealt": 29847,
                "physicalDamageDealt": 8540,
                "trueDamageDealt": 1570,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 3477,
                "magicDamageDealtToChampions": 2598,
                "physicalDamageDealtToChampions": 878,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 281,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 10233,
                "damageDealtToObjectives": 3323,
                "damageDealtToTurrets": 3323,
                "visionScore": 0,
                "timeCCingOthers": 2,
                "totalDamageTaken": 15995,
                "magicalDamageTaken": 301,
                "physicalDamageTaken": 15694,
                "trueDamageTaken": 0,
                "goldEarned": 5009,
                "goldSpent": 200,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 44,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 8,
                "champLevel": 12,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 0,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8437,
                "perk0Var1": 507,
                "perk0Var2": 346,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 1303,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8444,
                "perk2Var1": 591,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 130,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8224,
                "perk4Var1": 235,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8237,
                "perk5Var1": 79,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5002,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 10,
                "creepsPerMinDeltas": {
                    "10-20": 2.3,
                    "0-10": 1.8
                },
                "xpPerMinDeltas": {
                    "10-20": 404.4,
                    "0-10": 420
                },
                "goldPerMinDeltas": {
                    "10-20": 200.5,
                    "0-10": 222.8
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1067,
                    "0-10": 254.6
                },
                "role": "DUO_CARRY",
                "lane": "TOP"
            }
        }
    ],
    "participantIdentities": [
        {
            "participantId": 1,
            "player": {
                "platformId": "LA1",
                "accountId": "VdHUxIgdGfoGtuQscRPfSzwOw1ev3NOvo8_l_amCyU5Q9YRGws92UV4s",
                "summonerName": "NicolleCastro1",
                "summonerId": "NoN1Qxta-xVLdhdRb16kwa2SX2MPrAK5cNK6uLoOpBPY6-o",
                "currentPlatformId": "LA1",
                "currentAccountId": "VdHUxIgdGfoGtuQscRPfSzwOw1ev3NOvo8_l_amCyU5Q9YRGws92UV4s",
                "matchHistoryUri": "/v1/stats/player_history/LA1/2460033310075328",
                "profileIcon": 29
            }
        },
        {
            "participantId": 2,
            "player": {
                "platformId": "LA1",
                "accountId": "6wmzK1oapNJr3SFwV6ZmhiMU2d2THXlerHOMoqfeCNx_Rh8IfYIMF_6P",
                "summonerName": "NerOde67",
                "summonerId": "XsIQjukmJRBahaQw3oJovuRRGPpgKgfwMCgysHBz5bMdLVo",
                "currentPlatformId": "LA1",
                "currentAccountId": "6wmzK1oapNJr3SFwV6ZmhiMU2d2THXlerHOMoqfeCNx_Rh8IfYIMF_6P",
                "matchHistoryUri": "/v1/stats/player_history/LA1/2459400688436800",
                "profileIcon": 29
            }
        },
        {
            "participantId": 3,
            "player": {
                "platformId": "LA1",
                "accountId": "RxaUhcmh5GED0vD2-nApC9bWSrQEIeeTfIFhbd517kUlkHkE02YleUeO",
                "summonerName": "Posemindgio",
                "summonerId": "FOy1_Bbb4QO97al_aZ7ZLTMhZLTjBFebmfLRlG-18StZ6xU",
                "currentPlatformId": "LA1",
                "currentAccountId": "RxaUhcmh5GED0vD2-nApC9bWSrQEIeeTfIFhbd517kUlkHkE02YleUeO",
                "matchHistoryUri": "/v1/stats/player_history/LA1/2452487756163552",
                "profileIcon": 3542
            }
        },
        {
            "participantId": 4,
            "player": {
                "platformId": "LA1",
                "accountId": "2MnPsNrBhTKHSmKm3VixWOYzgxyn8PalQ3qQKDGWFM8JtOuGczgRONpx",
                "summonerName": "Chatoot",
                "summonerId": "qUZYyUxSE8wfZ8CPill4I1YZ1rsTqi8GJHXwmGcnQM9tyfw",
                "currentPlatformId": "LA1",
                "currentAccountId": "2MnPsNrBhTKHSmKm3VixWOYzgxyn8PalQ3qQKDGWFM8JtOuGczgRONpx",
                "matchHistoryUri": "/v1/stats/player_history/LA1/2458231581600192",
                "profileIcon": 23
            }
        },
        {
            "participantId": 5,
            "player": {
                "platformId": "LA1",
                "accountId": "-a5BZhSiCK5KJKiYae96JG_f4z2uAlhMa-MMdnzFbR51N8o45wCvbUK2",
                "summonerName": "The killerblack0",
                "summonerId": "WfX4UZpiuJxOlHYbSuPUJWgrfcIG1LXAOBrOlANT9u9Rx9Y",
                "currentPlatformId": "LA1",
                "currentAccountId": "-a5BZhSiCK5KJKiYae96JG_f4z2uAlhMa-MMdnzFbR51N8o45wCvbUK2",
                "matchHistoryUri": "/v1/stats/player_history/LA1/2392028997684064",
                "profileIcon": 3839
            }
        },
        {
            "participantId": 6,
            "player": {
                "platformId": "",
                "accountId": "0",
                "summonerName": "Ezreal",
                "currentPlatformId": "LA1",
                "currentAccountId": "0",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "profileIcon": 0
            }
        },
        {
            "participantId": 7,
            "player": {
                "platformId": "",
                "accountId": "0",
                "summonerName": "Nasus",
                "currentPlatformId": "LA1",
                "currentAccountId": "0",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "profileIcon": 0
            }
        },
        {
            "participantId": 8,
            "player": {
                "platformId": "",
                "accountId": "0",
                "summonerName": "Ryze",
                "currentPlatformId": "LA1",
                "currentAccountId": "0",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "profileIcon": 0
            }
        },
        {
            "participantId": 9,
            "player": {
                "platformId": "",
                "accountId": "0",
                "summonerName": "Alistar",
                "currentPlatformId": "LA1",
                "currentAccountId": "0",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "profileIcon": 0
            }
        },
        {
            "participantId": 10,
            "player": {
                "platformId": "",
                "accountId": "0",
                "summonerName": "Galio",
                "currentPlatformId": "LA1",
                "currentAccountId": "0",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "profileIcon": 0
            }
        }
    ]
};